<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--  Generated by org.testng.reporters.JUnitXMLReporter  --><testsuite errors="0" failures="3" hostname="USHYDMMEDAVARA3" ignored="0" name="Test" tests="3" time="45.958" timestamp="28 Mar 2018 06:16:20 GMT">
<testcase classname="Validating New Zeleand" name="test1" time="23.415">
<failure message="Unable to validate this condition against given value..." type="java.lang.AssertionError">&lt;![CDATA[java.lang.AssertionError: Unable to verify test expected [false] but found [true]at org.sample.AppTest.test1(AppTest.java:50)... Removed 28 stack frames]]&gt;</failure>
</testcase>
<testcase classname="Validating New Zeleand" name="test2" time="23.415">
<failure message="Unable to validate this condition against given value..." type="java.lang.AssertionError">&lt;![CDATA[java.lang.AssertionError: Unable to verify test expected [false] but found [true]at org.sample.AppTest.test1(AppTest.java:50)... Removed 28 stack frames]]&gt;</failure>
</testcase>
</testsuite>
